from enum import Enum


class Tasks(Enum):
    N_SAMPLE_DIFF_SCORE_RM = "N_SAMPLE_DIFF_SCORE_RM"
    N_SAMPLE_DIFF_SCORE_OTHER = "N_SAMPLE_DIFF_SCORE_OTHER"
    N_SAMPLES_FIRST = "N_SAMPLES_FIRST"
    EXISTING_M = "EXISTING_METHODS"
    STATIC_METHODS = "STATIC_METHODS"
    DYNAMIC_CORRECT_ALL = "DYNAMIC_CORRECT_ALL"
    DYNAMIC_CORRECT_NO_EXAMPLE = "DYNAMIC_CORRECT_NO_EXAMPLE"
    DYNAMIC_REWARD_MT = "DYNAMIC_REWARD_MT"
    DYNAMIC_REWARD_MM = "DYNAMIC_REWARD_MM"
    MANUAL_ITERATE = "MANUAL_ITERATE"
    NOT_CHOSEN = "NOT_CHOSEN"
