from enum import Enum


class Tasks(Enum):
    N_SAMPLE_DIFF_SCORE_RM = "N_SAMPLE_DIFF_SCORE_RM"
    N_SAMPLE_DIFF_SCORE_OTHER = "N_SAMPLE_DIFF_SCORE_OTHER"
    EXISTING_M = "EXISTING_METHODS"
    STATIC_METHODS = "STATIC_METHODS"
    NOT_CHOSEN = "NOT_CHOSEN"
